function getAccessToken() {
 return new Promise(function(resolve, reject) {
   const key = require('../placeholders/service-account.json');
   const jwtClient = new google.auth.JWT(
     key.client_email,
     null,
     key.private_key,
     SCOPES,
     null
   );
   jwtClient.authorize(function(err, tokens) {
     if (err) {
       reject(err);
       return;
     }
     resolve(tokens.access_token);
   });
 });
}
